### ISSUE TITLE
not working on RN 47.1

### ISSUE THREAD

**Issue by JaxGit** [oblador/react-native-parallax#27]
After upgrade with "react": "16.0.0-alpha.12", "react-native": "0.47.1", the example is running, however no parallax effects could be seen

**Comment by wootwoot1234** [comment]
@oblador I'm having the same issue.  I've spent hours trying to get it to work but I can't get a parallax effect to work.  Would you mind taking a look?  Here's a link to my fork with updates to make it build but no effects (sorry about the formatting, my files are auto formatted on save).  

https://github.com/wootwoot1234/react-native-parallax

**Comment by a-morenovalls** [comment]
Hey! Checkout our fork, it supports RN 49.0.3 and the new `PropTypes` reference. Parallax effect is working too.

Edit: here's the link.
https://github.com/APSL/react-native-parallax

**Comment by tan0300** [comment]
Hi @Moreno97, I've updated the module base on the APSL repository of react native parallax but I seem to have encountered new issue

undefined is not a function evaluating '(_this._touchable || _this._container).measure(_this.handleMeasure)')

What seems to be the problem?

**Comment by a-morenovalls** [comment]
Hey @tan0300 , it was a mistake on `componentWillReceiveProps`. I think it's fixed with this new change, if is not fixed please provide me the code that you are using, here it's working all fine.

**Comment by imaddev** [comment]
Hi @Moreno97 I think you need to change the [line 103](https://github.com/APSL/react-native-parallax/blob/master/ParallaxImage.js#L103) `<Animated.View` to `<View` only, that's worked for me

**Comment by a-morenovalls** [comment]
@imaddev that's weird, despite this I will look closely. Thanks!
